/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import controlador.Controlador;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import dao.ActividadVO;
import java.sql.SQLException;
import javax.swing.UIManager;

/**
 *
 * @author edusandovall
 */
public class GastoGUI extends javax.swing.JFrame {

   ActividadVO actividadVO = new ActividadVO();
   Controlador control = new Controlador();
       
    
    public GastoGUI() {
        initComponents();
        TableModel model;
        listarActividades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGasto = new javax.swing.JPanel();
        btnRefrescar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblTotalGastadoDia = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        lblGastoTotalFecha = new javax.swing.JLabel();
        lblShowTotalMes = new javax.swing.JLabel();
        btnMostrarTodo = new javax.swing.JButton();
        lblAcumulado = new javax.swing.JLabel();
        lblShowAcumulado = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblDescripcion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlGastos = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAllGastos = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGasto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGastoAcumulado = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblGastoMensual = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        lblIngoGastoDia = new javax.swing.JLabel();
        lblIngoGastoAcumulado = new javax.swing.JLabel();
        lblShowOneFechaAcumulado = new javax.swing.JLabel();
        lblAnd = new javax.swing.JLabel();
        lblShowTwoFechaAcumulado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblShowMonthGastoMes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblShowYearGastoMes = new javax.swing.JLabel();
        lblShowFechaGastoDia = new javax.swing.JLabel();
        lblPesos = new javax.swing.JLabel();
        lblPesos1 = new javax.swing.JLabel();
        lblPesos2 = new javax.swing.JLabel();
        btnModificarGastos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gasto Diario");
        setName("Gasto Diario"); // NOI18N
        setResizable(false);

        btnRefrescar.setMnemonic('R');
        btnRefrescar.setText("Mostrar Gasto");
        btnRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        lblTotal.setText("Total Gastado en el dia:");

        lblTotalGastadoDia.setText("-");

        jdcFecha.setDateFormatString("dd/MM/yyyy");
        jdcFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdcFechaMouseClicked(evt);
            }
        });

        lblGastoTotalFecha.setText("Total Gastado en el mes:");

        lblShowTotalMes.setText("-");

        btnMostrarTodo.setText("Ver Todos los Datos");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        lblAcumulado.setText("Total Acumulado");

        lblShowAcumulado.setText("-");

        lblDescripcion.setText("Seleccione una fecha:");

        tblAllGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblAllGastos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );

        pnlGastos.addTab("Todos los gastos", jPanel4);

        tblGasto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblGasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblGastoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblGasto);

        pnlGastos.addTab("Gasto Diario", jScrollPane1);

        tblGastoAcumulado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblGastoAcumulado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlGastos.addTab("Gasto Acumulado", jPanel1);

        tblGastoMensual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblGastoMensual);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlGastos.addTab("Gasto Mensual", jPanel2);

        lblIngoGastoDia.setText("Equivale al gasto en la fecha:");

        lblIngoGastoAcumulado.setText("Equivale al gasto entre ");

        lblShowOneFechaAcumulado.setText("-");

        lblAnd.setText("&");

        lblShowTwoFechaAcumulado.setText("-");

        jLabel1.setText("Equivale al gasto en el mes:");

        lblShowMonthGastoMes.setText("-");

        jLabel6.setText("del año");

        lblShowYearGastoMes.setText("-");

        lblShowFechaGastoDia.setText("-");

        lblPesos.setText("$");

        lblPesos1.setText("$");

        lblPesos2.setText("$");

        btnModificarGastos.setText("Modificar Gastos");
        btnModificarGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarGastosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGastoLayout = new javax.swing.GroupLayout(panelGasto);
        panelGasto.setLayout(panelGastoLayout);
        panelGastoLayout.setHorizontalGroup(
            panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGastoLayout.createSequentialGroup()
                .addGroup(panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGastoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGastoLayout.createSequentialGroup()
                                        .addComponent(lblIngoGastoDia)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblShowFechaGastoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelGastoLayout.createSequentialGroup()
                                        .addComponent(lblGastoTotalFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPesos2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblShowTotalMes, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGastoLayout.createSequentialGroup()
                                            .addComponent(lblAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblPesos1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblShowAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelGastoLayout.createSequentialGroup()
                                            .addComponent(lblIngoGastoAcumulado)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblShowOneFechaAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblAnd)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblShowTwoFechaAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelGastoLayout.createSequentialGroup()
                                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblPesos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblTotalGastadoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)))
                            .addGroup(panelGastoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblShowMonthGastoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblShowYearGastoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGastoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(panelGastoLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(lblDescripcion)
                        .addGap(93, 93, 93)
                        .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnRefrescar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelGastoLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(btnMostrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificarGastos)
                .addGap(153, 153, 153))
        );
        panelGastoLayout.setVerticalGroup(
            panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGastoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefrescar)
                    .addComponent(lblDescripcion))
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelGastoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGastoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIngoGastoDia)
                            .addComponent(lblShowFechaGastoDia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(lblTotalGastadoDia)
                            .addComponent(lblPesos))
                        .addGap(18, 18, 18)
                        .addGroup(panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIngoGastoAcumulado)
                            .addComponent(lblShowOneFechaAcumulado)
                            .addComponent(lblAnd)
                            .addComponent(lblShowTwoFechaAcumulado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAcumulado)
                            .addComponent(lblPesos1)
                            .addComponent(lblShowAcumulado))
                        .addGap(18, 18, 18)
                        .addGroup(panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblShowMonthGastoMes)
                            .addComponent(jLabel6)
                            .addComponent(lblShowYearGastoMes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGastoTotalFecha)
                            .addComponent(lblPesos2)
                            .addComponent(lblShowTotalMes))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelGastoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarTodo)
                    .addComponent(btnModificarGastos))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void listarActividades()
    {
       try 
       {
           DefaultTableModel table = new DefaultTableModel();
           ArrayList<ActividadVO> listaActividades= new ArrayList();
           listaActividades = control.listarGasto();
           
           table.addColumn("Nombre Actividad");
           table.addColumn("Valor");
           table.addColumn("Categoria");
           table.addColumn("Fecha");
           table.setRowCount(listaActividades.size());
           
           int i=0;
           
           for(ActividadVO x:listaActividades)
           {
               table.setValueAt(x.getNombreGasto(), i, 0);
               table.setValueAt(x.getValorGasto(), i, 1);
               table.setValueAt(x.getCategoriaGasto(), i, 2);
               table.setValueAt(x.getFechaGasto(), i, 3);
               i++;
           }
           
           this.tblAllGastos.setModel(table);
           
       } 
       catch (Exception ex) {
           Logger.getLogger(GastoGUI.class.getName()).log(Level.SEVERE, null, ex);
       }
    }
    
    public void calcularGastos(String date)
    {
           int gastoTotal;
           int gastoTotalFecha;
           int gastoAcumulado;
           
           gastoTotal= control.enviarFechaInt(date);
           lblTotalGastadoDia.setText(String.valueOf(gastoTotal));
           
           gastoTotalFecha = control.enviarFechaIntGT(date);
           lblShowTotalMes.setText(String.valueOf(gastoTotalFecha));
           
           gastoAcumulado = control.enviarFechaIntAcum(date);
           lblShowAcumulado.setText(String.valueOf(gastoAcumulado));
    }
    
    public void gastoDiario(String date)
    {
        DefaultTableModel table = new DefaultTableModel();
           ArrayList<ActividadVO> listaActividades= new ArrayList();
           listaActividades = control.enviarFecha(date);
           
           table.addColumn("Nombre Actividad");
           table.addColumn("Valor");
           table.addColumn("Categoria");
           table.addColumn("Fecha");
           table.setRowCount(listaActividades.size());
           
           int i=0;
           
           for(ActividadVO x:listaActividades)
           {
               table.setValueAt(x.getNombreGasto(), i, 0);
               table.setValueAt(x.getValorGasto(), i, 1);
               table.setValueAt(x.getCategoriaGasto(), i, 2);
               table.setValueAt(x.getFechaGasto(), i, 3);
               i++;
           }
           
           this.tblGasto.setModel(table);
    }
    
    public void gastoMensual(String date)
    {
        DefaultTableModel table = new DefaultTableModel();
           ArrayList<ActividadVO> listaActividades= new ArrayList();
           listaActividades = control.enviarFechaMensual(date);
           
           table.addColumn("Nombre Actividad");
           table.addColumn("Valor");
           table.addColumn("Categoria");
           table.addColumn("Fecha");
           table.setRowCount(listaActividades.size());
           
           int i=0;
           
           for(ActividadVO x:listaActividades)
           {
               table.setValueAt(x.getNombreGasto(), i, 0);
               table.setValueAt(x.getValorGasto(), i, 1);
               table.setValueAt(x.getCategoriaGasto(), i, 2);
               table.setValueAt(x.getFechaGasto(), i, 3);
               i++;
           }
           
           this.tblGastoMensual.setModel(table);
    }
    
    public void gastoAcumulado(String date)
    {
       try {
           DefaultTableModel table = new DefaultTableModel();
          ArrayList<ActividadVO> listaActividades= new ArrayList();
          listaActividades = control.enviarFechaAcumulado(date);

          table.addColumn("Nombre Actividad");
          table.addColumn("Valor");
          table.addColumn("Categoria");
          table.addColumn("Fecha");
          table.setRowCount(listaActividades.size());

          int i=0;

          for(ActividadVO x:listaActividades)
          {
              table.setValueAt(x.getNombreGasto(), i, 0);
              table.setValueAt(x.getValorGasto(), i, 1);
              table.setValueAt(x.getCategoriaGasto(), i, 2);
              table.setValueAt(x.getFechaGasto(), i, 3);
              i++;
          }

          this.tblGastoAcumulado.setModel(table);
          
       } catch (SQLException | ClassNotFoundException ex) {
           Logger.getLogger(GastoGUI.class.getName()).log(Level.SEVERE, null, ex);
       }
    }
    
    public String mesObtenido(String date)
    {
        int mes;
        String mesT="";
        mes= Integer.parseInt(date.substring(3, 5));
        
        switch(mes)
        {
            case 01:  mesT = "Enero";
                return mesT;
            case 02: mesT = "Febrero";
                return mesT;
            case 03: mesT = "Marzo";
                return mesT;
            case 04:  mesT = "Abril";
                return mesT;
            case 05:  mesT = "Mayo";
                return mesT;
            case 06:  mesT = "Junio";
                return mesT;
            case 07:  mesT = "Julio";
                return mesT;
            case 8: mesT = "Agosto";
                return mesT;
            case 9:  mesT = "Septiembre";
                return mesT;
            case 10:  mesT = "Octubre";
                return mesT;
            case 11:  mesT = "Noviembre";
                return mesT;
            case 12:  mesT = "Diciembre";
                return mesT;
        }
       return mesT;
    }
    
    public void mostrarFechas(String date)
    {
        String mes;
        String año;
        String fechaUno;
        String mesAño;
        
        mesAño = date.substring(3, 10);
        fechaUno = "01/"+mesAño;
        mes = mesObtenido(date);
        año= date.substring(6);
        
        lblShowFechaGastoDia.setText(date);
        lblShowOneFechaAcumulado.setText(fechaUno);
        lblShowTwoFechaAcumulado.setText(date);
        lblShowMonthGastoMes.setText(mes);
        lblShowYearGastoMes.setText(año);
    }
    
    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        String date;
        
        date = ((JTextField)jdcFecha.getDateEditor().getUiComponent()).getText();
        
        gastoDiario(date);
        gastoAcumulado(date);
        gastoMensual(date);
        calcularGastos(date);
        mostrarFechas(date);
           
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void jdcFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdcFechaMouseClicked
        
        
    }//GEN-LAST:event_jdcFechaMouseClicked

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        lblShowTotalMes.setText("-");
        lblTotalGastadoDia.setText("-");
        lblShowAcumulado.setText("-");
        listarActividades();
        
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void tblGastoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGastoMousePressed

    }//GEN-LAST:event_tblGastoMousePressed

    private void btnModificarGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarGastosActionPerformed
        ModificarGasto modGasto = new ModificarGasto(new GastoGUI(), true);
        modGasto.setVisible(true);
    }//GEN-LAST:event_btnModificarGastosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
//                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
//                 UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
               
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GastoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GastoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GastoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GastoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GastoGUI().setVisible(true);
            }
        });
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarGastos;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JLabel lblAcumulado;
    private javax.swing.JLabel lblAnd;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblGastoTotalFecha;
    private javax.swing.JLabel lblIngoGastoAcumulado;
    private javax.swing.JLabel lblIngoGastoDia;
    private javax.swing.JLabel lblPesos;
    private javax.swing.JLabel lblPesos1;
    private javax.swing.JLabel lblPesos2;
    private javax.swing.JLabel lblShowAcumulado;
    private javax.swing.JLabel lblShowFechaGastoDia;
    private javax.swing.JLabel lblShowMonthGastoMes;
    private javax.swing.JLabel lblShowOneFechaAcumulado;
    private javax.swing.JLabel lblShowTotalMes;
    private javax.swing.JLabel lblShowTwoFechaAcumulado;
    private javax.swing.JLabel lblShowYearGastoMes;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalGastadoDia;
    private javax.swing.JPanel panelGasto;
    private javax.swing.JTabbedPane pnlGastos;
    private javax.swing.JTable tblAllGastos;
    private javax.swing.JTable tblGasto;
    private javax.swing.JTable tblGastoAcumulado;
    private javax.swing.JTable tblGastoMensual;
    // End of variables declaration//GEN-END:variables
}
