/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import controlador.Controlador;
import dao.ActividadVO;
import dao.CategoriaVO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edusandovall
 */
public class ModificarGasto extends javax.swing.JDialog {

    Controlador control = new Controlador();
    GastoGUI gasto = new GastoGUI();
    /**
     * Creates new form ModificarGasto
     */
    public ModificarGasto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listarActividades();
    }
    
    public void listarActividades()
    {
       try 
       {
           DefaultTableModel table = new DefaultTableModel();
           ArrayList<ActividadVO> listaActividades= new ArrayList();
           listaActividades = control.listarGasto();
           
           table.addColumn("Id Gasto");
           table.addColumn("Nombre Actividad");
           table.addColumn("Valor");
           table.addColumn("Categoria");
           table.addColumn("Fecha");
           table.setRowCount(listaActividades.size());
           
           int i=0;
           
           for(ActividadVO x:listaActividades)
           {
               table.setValueAt(x.getIdGasto(), i, 0);
               table.setValueAt(x.getNombreGasto(), i, 1);
               table.setValueAt(x.getValorGasto(), i, 2);
               table.setValueAt(x.getCategoriaGasto(), i, 3);
               table.setValueAt(x.getFechaGasto(), i, 4);
               i++;
           }
           
           this.tblGastos.setModel(table);
           
       } 
       catch (Exception ex) {
           Logger.getLogger(GastoGUI.class.getName()).log(Level.SEVERE, null, ex);
       }
    }
    
    public void gastoMensual(String date)
    {
        DefaultTableModel table = new DefaultTableModel();
           ArrayList<ActividadVO> listaActividades= new ArrayList();
           listaActividades = control.enviarFechaMensual(date);
           
           table.addColumn("Id Gasto");
           table.addColumn("Nombre Actividad");
           table.addColumn("Valor");
           table.addColumn("Categoria");
           table.addColumn("Fecha");
           table.setRowCount(listaActividades.size());
           
           int i=0;
           
           for(ActividadVO x:listaActividades)
           {
               table.setValueAt(x.getIdGasto(), i, 0);
               table.setValueAt(x.getNombreGasto(), i, 1);
               table.setValueAt(x.getValorGasto(), i, 2);
               table.setValueAt(x.getCategoriaGasto(), i, 3);
               table.setValueAt(x.getFechaGasto(), i, 4);
               i++;
           }
           
           this.tblGastos.setModel(table);
    }
    
    public void listarCategoria()
    {
        try {
            
            String seleccion = "Seleccione:";
            
           DefaultComboBoxModel combo = new DefaultComboBoxModel();
           ArrayList<CategoriaVO> listaCategoria = new ArrayList();
           combo.insertElementAt(seleccion, 0);
           listaCategoria = control.listarCategorias();
           
           for(CategoriaVO x:listaCategoria)
           {
              combo.insertElementAt(x.getCategoriaName(), x.getIdCategoria());
           }
           
           this.cbxCategoria.setModel(combo);
           
       } catch (ClassNotFoundException | SQLException ex) {
           Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGastos = new javax.swing.JTable();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        btnMostraFecha = new javax.swing.JButton();
        btnMostrarAllGastos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblGasto = new javax.swing.JLabel();
        lblNombreGasto = new javax.swing.JLabel();
        lblValorGasto = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtValorGasto = new javax.swing.JTextField();
        txtNombreGasto = new javax.swing.JTextField();
        cbxCategoria = new javax.swing.JComboBox();
        jdcFechaSeleccion = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();
        lblShowId = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblSeleccionFecha = new javax.swing.JLabel();
        lblSeleccionGasto = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Gasto");
        setResizable(false);

        tblGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGastosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGastos);

        jdcFecha.setDateFormatString("dd/MM/yyyy");
        jdcFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdcFechaMouseClicked(evt);
            }
        });

        btnMostraFecha.setText("Mostrar por Mes");
        btnMostraFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostraFechaActionPerformed(evt);
            }
        });

        btnMostrarAllGastos.setText("Mostrar Todo");
        btnMostrarAllGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAllGastosActionPerformed(evt);
            }
        });

        lblGasto.setText("ID Gasto");

        lblNombreGasto.setText("Nombre del Gasto");

        lblValorGasto.setText("Valor del gasto");

        lblCategoria.setText("Categoria");

        lblFecha.setText("Fecha");

        cbxCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbxCategoriaMouseReleased(evt);
            }
        });

        jdcFechaSeleccion.setDateFormatString("dd/MM/yyyy");
        jdcFechaSeleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdcFechaSeleccionMouseClicked(evt);
            }
        });

        lblShowId.setText("-");

        lblSeleccionFecha.setText("Seleccione la fecha a modificar");

        lblSeleccionGasto.setText("Seleccione el Gasto a Modificar");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSeleccionGasto)
                .addGap(145, 145, 145))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtValorGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombreGasto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblShowId, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdcFechaSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnNuevo)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblValorGasto)
                                        .addComponent(lblCategoria)
                                        .addComponent(lblGasto)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblSeleccionFecha)
                        .addGap(90, 90, 90)
                        .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnMostraFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addGap(418, 418, 418)
                        .addComponent(btnMostrarAllGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMostraFecha))
                    .addComponent(lblSeleccionFecha, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSeleccionGasto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGasto)
                            .addComponent(lblShowId))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNombreGasto)
                                            .addComponent(txtNombreGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblValorGasto)
                                            .addComponent(txtValorGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCategoria))
                                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblFecha))
                            .addComponent(jdcFechaSeleccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarAllGastos)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnNuevo))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jdcFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdcFechaMouseClicked

    }//GEN-LAST:event_jdcFechaMouseClicked

    private void jdcFechaSeleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdcFechaSeleccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jdcFechaSeleccionMouseClicked

    private void btnMostraFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostraFechaActionPerformed
        String date;
        
        date = ((JTextField)jdcFecha.getDateEditor().getUiComponent()).getText();
        
        gastoMensual(date);
    }//GEN-LAST:event_btnMostraFechaActionPerformed

    private void btnMostrarAllGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAllGastosActionPerformed
        listarActividades();
    }//GEN-LAST:event_btnMostrarAllGastosActionPerformed

    private void cbxCategoriaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxCategoriaMouseReleased
        listarCategoria();
    }//GEN-LAST:event_cbxCategoriaMouseReleased

    private void tblGastosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGastosMouseClicked
       
        int row = tblGastos.getSelectedRow();
        String clickTable = (tblGastos).getModel().getValueAt(row, 0).toString();
        
        ArrayList<ActividadVO> listaActividades= new ArrayList();
        listaActividades = control.gastoPorID(Integer.parseInt(clickTable));
        cbxCategoria.removeAllItems();
        
        for(ActividadVO x:listaActividades)
        {
            lblShowId.setText(String.valueOf(x.getIdGasto()));
            txtNombreGasto.setText(x.getNombreGasto());
            txtValorGasto.setText(String.valueOf(x.getValorGasto()));
            cbxCategoria.addItem(x.getCategoriaGasto());
            ((JTextField)jdcFechaSeleccion.getDateEditor().getUiComponent()).setText(x.getFechaGasto().substring(0, 10 ));
        }
    }//GEN-LAST:event_tblGastosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        int id;
        String nombre;
        int valor;
        int categoria;
        String fecha;
        
        id = Integer.parseInt(lblShowId.getText());
        nombre = txtNombreGasto.getText();
        valor = Integer.parseInt(txtValorGasto.getText());
        categoria = cbxCategoria.getSelectedIndex();
        fecha = ((JTextField)jdcFechaSeleccion.getDateEditor().getUiComponent()).getText();
        
        if(control.actualizarDatos(id, nombre, valor, fecha, categoria)==true)
        {
            JOptionPane.showMessageDialog(null, "El gasto ha sido actualizado con exito", "Mensaje", 1);
            listarActividades();
            gasto.listarActividades();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No se ha podido actualizar el gasto", "Mensaje", 0);
        }
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
            Registro modGasto = new Registro(new GastoGUI(), true);
            modGasto.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        int id;
        
        id = Integer.parseInt(lblShowId.getText());
        
        if(control.eliminarGasto(id)==true)
        {
            JOptionPane.showMessageDialog(null, "El gasto ha sido eliminado", "Mensaje", 1);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No se ha podido eliminar el gasto", "Mensaje", 0);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarGasto dialog = new ModificarGasto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMostraFecha;
    private javax.swing.JButton btnMostrarAllGastos;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cbxCategoria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private com.toedter.calendar.JDateChooser jdcFechaSeleccion;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblGasto;
    private javax.swing.JLabel lblNombreGasto;
    private javax.swing.JLabel lblSeleccionFecha;
    private javax.swing.JLabel lblSeleccionGasto;
    private javax.swing.JLabel lblShowId;
    private javax.swing.JLabel lblValorGasto;
    private javax.swing.JTable tblGastos;
    private javax.swing.JTextField txtNombreGasto;
    private javax.swing.JTextField txtValorGasto;
    // End of variables declaration//GEN-END:variables
}
