/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import controlador.Controlador;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import dao.CategoriaVO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author edusandovall
 */
public class Registro extends javax.swing.JDialog {
    
   Controlador control = new Controlador();
   ModificarGasto modGasto = new ModificarGasto(new GastoGUI(), true);
   GastoGUI gasto = new GastoGUI();
   
    public Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        limpiar();
//        listarCategoria();
    }
    
    public final void limpiar()
    {
        txtNombreGasto.setText("");
        txtValor.setText("");
    }

    public void listarCategoria()
    {
        try {
            
            String seleccion = "Seleccione:";
            
           DefaultComboBoxModel combo = new DefaultComboBoxModel();
           ArrayList<CategoriaVO> listaCategoria = new ArrayList();
           combo.insertElementAt(seleccion, 0);
           listaCategoria = control.listarCategorias();
           
           for(CategoriaVO x:listaCategoria)
           {
              combo.insertElementAt(x.getCategoriaName(), x.getIdCategoria());
           }
           
           this.cbxCategoria.setModel(combo);
           
       } catch (ClassNotFoundException | SQLException ex) {
           Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRegistro = new javax.swing.JPanel();
        lblNombreGasto = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox();
        txtNombreGasto = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        btnAgregarCategoria = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro ");
        setResizable(false);

        lblNombreGasto.setText("Nombre del Gasto");

        lblValor.setText("Valor");

        lblCategoria.setText("Categoria");

        lblFecha.setText("Fecha");

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        cbxCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxCategoriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbxCategoriaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbxCategoriaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbxCategoriaMouseReleased(evt);
            }
        });
        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jdcFecha.setDateFormatString("d/MM/yyyy");

        btnAgregarCategoria.setIcon(new javax.swing.ImageIcon("/home/edusandovall/Pictures/agregar-planes.png")); // NOI18N
        btnAgregarCategoria.setToolTipText("Agregar Categoria");
        btnAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCategoriaActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon("/home/edusandovall/Pictures/Boton-actuaqlizacion-de-Datos.gif")); // NOI18N
        btnActualizar.setToolTipText("Actualizar Categoria");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnRegistroLayout = new javax.swing.GroupLayout(jpnRegistro);
        jpnRegistro.setLayout(jpnRegistroLayout);
        jpnRegistroLayout.setHorizontalGroup(
            jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRegistroLayout.createSequentialGroup()
                .addGroup(jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnRegistroLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreGasto)
                            .addGroup(jpnRegistroLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategoria)
                                    .addComponent(lblValor)
                                    .addComponent(lblFecha))
                                .addGap(97, 97, 97)
                                .addGroup(jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreGasto)
                                    .addComponent(cbxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtValor)
                                    .addComponent(jdcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))))
                    .addGroup(jpnRegistroLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(32, 32, 32)))
                .addComponent(btnAgregarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpnRegistroLayout.setVerticalGroup(
            jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRegistroLayout.createSequentialGroup()
                .addGroup(jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnRegistroLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnRegistroLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreGasto)
                            .addComponent(txtNombreGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValor)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFecha)
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jpnRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    
           String nombreGasto = txtNombreGasto.getText();
           int valorGasto = Integer.parseInt(txtValor.getText());
           String fecha = ((JTextField)jdcFecha.getDateEditor().getUiComponent()).getText();
           int idCategoria = cbxCategoria.getSelectedIndex();
           
           if(idCategoria==0)
           {
               JOptionPane.showMessageDialog(null, "Por favor seleccione una categoria", "Mensaje", 1);
           }
           else if(control.enviarDatos(nombreGasto, valorGasto, fecha, idCategoria)==true)
           {
               JOptionPane.showMessageDialog(null, "Ingreso Exitoso", "Mensaje", 1);
               limpiar();
               
               modGasto.listarActividades();
               gasto.listarActividades();
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "Mensaje", 2);
               limpiar();
           }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbxCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxCategoriaMousePressed
       
    }//GEN-LAST:event_cbxCategoriaMousePressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
     dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbxCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxCategoriaMouseClicked

    }//GEN-LAST:event_cbxCategoriaMouseClicked

    private void cbxCategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxCategoriaMouseEntered
       // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaMouseEntered

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void cbxCategoriaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxCategoriaMouseReleased
        listarCategoria();  // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaMouseReleased

    private void btnAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCategoriaActionPerformed
        Categoria categoria = new Categoria(new GastoGUI(), true);
        categoria.setVisible(true);
    }//GEN-LAST:event_btnAgregarCategoriaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        ActualizarCategoria updCategoria = new ActualizarCategoria(new GastoGUI(), true);
        updCategoria.setVisible(true);
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               Registro dialog = new Registro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarCategoria;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbxCategoria;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JPanel jpnRegistro;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombreGasto;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtNombreGasto;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
